# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepositorioDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conexao', models.CharField(max_length=200)),
                ('dml', models.CharField(max_length=200)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.Ambiente')),
            ],
        ),
    ]
